parameters:
  - name: x_api_consumer
    type: string
  - name: x_api_key
    type: string
  - name: api_host
    type: string
    default: 'https://app-aep-api-s-latest-uksouth.azurewebsites.net'
  - name: working_directory
    displayName: 'The working directory must include trailing slash'
    type: string
    default: '$(System.DefaultWorkingDirectory)/'


stages:
  - stage: GenAIPullRequestReview
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
     - job: GenAIChecks
       steps: 
        - checkout: 'self'
          submodules: 'true'
          fetchDepth: 0  # Set fetch depth to 0
          persistCredentials: true
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
            addToPath: true
            architecture: 'x64'
        - task: Bash@3
          displayName: 'Generate diff as text file'
          inputs:
            targetType: 'inline'
            script: |
              echo "Checking out main/master branch..."
              git checkout $(System.PullRequest.TargetBranchName)
              echo "Pulling latest changes from remote..."
              git pull origin $(System.PullRequest.TargetBranchName)
              echo "Switching back to PR branch..."
              git checkout "$(System.PullRequest.SourceCommitId)"
              echo "Showing diff..."
              git diff $(System.PullRequest.TargetBranchName)...$(System.PullRequest.SourceCommitId) > ${{ parameters.working_directory }}diff.txt
        - task: Bash@3
          displayName: 'Generate markdown file'
          env: 
            WORKING_DIRECTORY: ${{ parameters.working_directory }}
            API_HOST: ${{ parameters.api_host }}
            X_API_CONSUMER: ${{ parameters.x_api_consumer }}
            X_API_KEY: ${{ parameters.x_api_key }}
          inputs:
            targetType: 'inline'
            script: |
              #!/bin/bash
              API_HOST=$(printenv API_HOST)
              WORKING_DIRECTORY=$(printenv WORKING_DIRECTORY)
              X_API_CONSUMER=$(printenv X_API_CONSUMER)
              X_API_KEY=$(printenv X_API_KEY)
              DIFF_FILE="diff.txt"
              RESPONSE_MD_FILE="response.md"

              if [ ! -f "${WORKING_DIRECTORY}${DIFF_FILE}" ]; then
                  echo "File ${WORKING_DIRECTORY}${DIFF_FILE} not found."
                  exit 1
              fi

              file_contents=$(cat "${WORKING_DIRECTORY}${DIFF_FILE}")
              json_body=$(jq -n --arg pt "pullrequest-review" --arg p "$file_contents" '{prompt_type: $pt, prompt: $p}')

              response=$(curl -s -i -X POST "${API_HOST}/predefined" \
                  -H "Content-Type: application/json" \
                  -H "X-API-CONSUMER: ${X_API_CONSUMER}" \
                  -H "X-API-KEY: ${X_API_KEY}" \
                  -d "$json_body")

              echo "Response: $response"

              response_code=$(echo "$response" | awk -F' ' '/HTTP\/1.1/{print $2}' | head -n 1)

              if [ "$response_code" -eq 200 ]; then
                  echo "File contents sent successfully."
                  # Remove headers
                  response_body=$(echo "$response" | tail -n +2)
                  # Remove more headers
                  response_body=$(echo "$response_body" | sed '/^date: /Id' | sed '/^server: /Id' | sed '/^content-length: /Id' | sed '/^content-type: /Id')
                  # remove trailing and leading quotes
                  response_body=$(echo "$response_body" | sed 's/^"\(.*\)"$/\1/')
                  # If the response body contains markdown prefix then remove it
                  if echo "$response_body" | grep -q '```markdown'; then
                    # remove the initial markdown code block ident if it exists
                    response_body=$(echo "$response_body" | sed 's/```markdown//')
                    # remove the last code block ident
                    response_body=$(echo "$response_body" | sed 's/```//')
                  fi
                  
                  # Write to file
                  echo -e "$response_body" > "${WORKING_DIRECTORY}${RESPONSE_MD_FILE}"
              else
                  echo "Error sending file contents: $response_code"
                  echo -e "Request to AEP failed to process" > "${WORKING_DIRECTORY}${RESPONSE_MD_FILE}"
              fi

              if [ $? -eq 0 ]; then
                  echo "Response saved as response.md"
              else
                  echo "Error writing to file in ${WORKING_DIRECTORY}."
                  exit 1
              fi

        - task: Bash@3
          displayName: 'Comment on the PR'
          inputs:
            targetType: 'inline'
            script: |
              COMMENT=$(<${{ parameters.working_directory }}response.md)
              ADO_API=$(echo "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1-preview.1" | sed -e 's/ /%20/g')
  
              PR_COMMENT=$(jq --arg comment "$COMMENT" '.comments[0].content = $comment' <<< '{"comments": [{"parentCommentId": 0,"content": "","commentType": 1}],"status": 1}')
  
              curl --request POST "$ADO_API" \
              --header "Content-Type: application/json" \
              --header "Accept: application/json" \
              --header "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
              --data "$PR_COMMENT" \
              --verbose
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)